### ISSUE TITLE
Better error message when unknown attribute is in select

### ISSUE THREAD

**Issue by nicolasgramlich** [SylvainEstevez/Restypie#15]
When defining a `defaultSelect` that has an attribute that's not in the `schema`, the error is as follows:

```shell
2000-01-01T00:00:00.000Z [RESTYPIE 1.3.5 ERROR] TypeError: Cannot read property 'path' of undefined
    at /Users/nico/Workspace/Server/some-api.someservice/node_modules/restypie/src/resources/lib/abstract-resource.js:697:35
    at Array.map (native)
    at CustomerResource.parseSelect (/Users/nico/Workspace/Server/some-api.someservice/node_modules/restypie/src/resources/lib/abstract-resource.js:696:29)
    at CustomerResource.pipeline.add (/Users/nico/Workspace/Server/some-api.someservice/node_modules/restypie/src/basic-routes/lib/get-many.js:28:18)
    at Promise.try (/Users/nico/Workspace/Server/some-api.someservice/node_modules/restypie/src/bundle/lib/task-pipeline.js:64:29)
```

Ideally the error message would be more descriptive about attempting a select on an undefined attribute.

**Comment by SylvainEstevez** [comment]
Solution : make the constructor check the values in `defaultSelect` at instantiation (somewhere around here https://github.com/SylvainEstevez/Restypie/blob/master/src/resources/lib/abstract-resource.js#L246). Basically all values in `defaultSelect` should be in the schema.
